---
- name: Install brew taps
  homebrew_tap:
    name: "{{ brew_taps }}"
    state: present
  tags: dotfiles_brew_taps

- name: Install brew packages
  homebrew:
    name: "{{ brew_packages }}"
    state: latest
    update_homebrew: true
    upgrade_all: true
  tags: dotfiles_brew_packages

- name: Install brew casks
  homebrew_cask:
    name: "{{ brew_casks }}"
    state: latest
    accept_external_apps: true
    update_homebrew: true
    upgrade_all: "{{ upgrade_casks }}"
  tags: dotfiles_brew_casks
...
