- name: Configure git
  copy:
    src: "git/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ ansible_env.USER }}"
    group: staff
    mode: '0755'
  loop:
    - .gitconfig
    - .gitignore_global
