---
- name: Configure iTerm2
  command: "defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder
    -int 1 && defaults write com.googlecode.iterm2 PrefsCustomFolder
    -string {{ role_path }}/files/iterm2"
  changed_when: false

- name: Activate iTerm2
  command: osascript -e 'tell application "iTerm" to activate"'
  changed_when: false
...
