---
- name: Load iTerm2 preferences from custom folder
  command: "defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder
    -int 1"
  changed_when: false

- name: Define folder to load iTerm2 preferences from
  command: "defaults write com.googlecode.iterm2 PrefsCustomFolder -string
    {{ role_path }}/files/iterm2"
  changed_when: false
...
